version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lamansiondeldragon
      MYSQL_USER: lamansion
      MYSQL_PASSWORD: lamansion
      MYSQL_ROOT_PASSWORD: lamansionroot

  server:
    depends_on:
      - db
    image: node:lts
    command: yarn docker
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    restart: always

  client:
    depends_on:
      - server
    image: node:lts
    command: yarn docker
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"

volumes:
  db_data: