version: '3.4'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - myapp_mysql_data:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
    networks:
      - lamansion

  server:
    links:
      - db
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; yarn docker'
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    restart: always
    networks:
      - lamansion

  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - lamansion

volumes:
  myapp_mysql_data:

networks:
  lamansion: